name: "Flatten P2 repository"
description: "Flatten a P2 repository to being able to host with Github Releases."
inputs:
  repository_path:
    description: "The P2 repository path."
    required: true
runs:
  using: "composite"
  steps:
    - name: "Flattening P2 repository"
      run: action.sh
      shell: bash
