name: "Flatten P2 repository"
description: "Flatten a P2 repository to being able to host with Github Releases."
inputs:
  repository_path:
    description: "The P2 repository path."
    required: true
  output_path:
    description: "The output path for the flatten P2 repository"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Flattening P2 repository"
      run: |
        cd ${{ github.action_path }}
        wget https://repo1.maven.org/maven2/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
        wget https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.jar
        java -cp "commons-io-2.15.1.jar;xz-1.9.jar" FlattenP2Repo.java
      shell: bash
