name: "Flatten P2 repository"
description: "Flatten a P2 repository to being able to host with Github Releases."
inputs:
  repository-path:
    description: "The P2 repository path."
    required: true
runs:
  using: "composite"
  env:
      CLASSPATH_SEPARATOR: ${{ runner.os == 'Windows' && ';' || ':' }}
  steps:
    - name: "Flattening P2 repository"
      run: |
        curl -o commons-io-2.15.1.jar https://repo1.maven.org/maven2/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
        curl -o xz-1.9.jar https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.jar
        export CLASSPATH=commons-io-2.15.1.jar${{ env.CLASSPATH_SEPARATOR }}xz-1.9.jar
        java FlattenP2Repo.java ${{ github.workspace }}/${{ inputs.repository-path }}
      working-directory: ${{ github.action_path }}
      shell: bash
